### ISSUE TITLE
Any possibility of a pre-compiled binary?

### ISSUE THREAD

**Issue by Laurence5905** [kalbert312/alienfx-cli#1]
Feature request:  Throw a pre-compiled binary up here, so we don't have to download Visual Studio Community 2017, learn how to use it, and compile this program.  Seriously, I know a lot about writing software, but I have zero experience in Visual Studio Community 2017, and I cannot imagine it will be easy to compile this thing given my complete lack of knowledge.  I just want something that will let me bind a macro key to turn off (and on) the keyboard lights -- I don't want to spend multiple hours learning how to use Visual Studio 2017.  Thanks.

**Comment by kalbert312** [comment]
Hi. There is already one here: https://github.com/kalbert312/alienfx-cli/releases which should work provided AlienFX is installed on your computer.

**Comment by Laurence5905** [comment]
Ahh!  Ok, then.  I totally didn't see that...  Sorry.  Thanks!

**Comment by kalbert312** [comment]
No worries. I blame GitHub. The small release tag page almost feels like a secret.
